// This file will be auto-generated by running:
// npx supabase gen types typescript --local > src/types/supabase.ts
// After you set up your database schema

export type Database = {
  public: {
    Tables: {
      // Your tables will be defined here after generation
      // Example structure:
      agents: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string
          name: string
          description: string | null
          platform: string
          configuration: any // JSONB
          is_public: boolean
          slug: string
          category: string | null
          tags: string[] | null
          download_count: number
          upvote_count: number
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id: string
          name: string
          description?: string | null
          platform: string
          configuration: any
          is_public?: boolean
          slug: string
          category?: string | null
          tags?: string[] | null
          download_count?: number
          upvote_count?: number
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id?: string
          name?: string
          description?: string | null
          platform?: string
          configuration?: any
          is_public?: boolean
          slug?: string
          category?: string | null
          tags?: string[] | null
          download_count?: number
          upvote_count?: number
        }
      }
      profiles: {
        Row: {
          id: string
          user_id: string
          username: string | null
          full_name: string | null
          bio: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          username?: string | null
          full_name?: string | null
          bio?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          username?: string | null
          full_name?: string | null
          bio?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      // Your views will be defined here
    }
    Functions: {
      // Your functions will be defined here
    }
    Enums: {
      // Your enums will be defined here
      platform_type: 'openai' | 'claude' | 'gemini' | 'langchain' | 'copilot' | 'other'
      category_type: 'productivity' | 'analysis' | 'documentation' | 'testing' | 'compliance' | 'other'
    }
  }
}